spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: false

jwt:
  token:
    secret: bWVudG9ycy1iYWNrZW5kLXNwcmluZy1ib290LWp3dC1zZWNyZXQtbWVudG9ycy1iYWNrZW5kLXNwcmluZy1ib290LWp3dC1zZWNyZXQ=
    access:
      expiration: 1800000
    refresh:
      expiration: 86400000