POST localhost:8080/api/v1/todo-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjoiMSIsImlhdCI6MTY4MTQ4NzAzOSwiZXhwIjoxNjgxNDg4ODM5fQ.EwJzkrnSg6U1pHZeYKc6yjm-gCEMf62RndS_E1Euj_4

{
  "title" : "title",
  "content" : "content",
  "hashTags" : ["hashtag1", "hashtag2", "hashtag3"],
  "subLists" : [{
    "content" : "subContent1"
  },{
    "content" : "subContent2"
  }]
}

###
PUT localhost:8080/api/v1/todo-list/1/complete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjoiMSIsImlhdCI6MTY4MTQ4NzAzOSwiZXhwIjoxNjgxNDg4ODM5fQ.EwJzkrnSg6U1pHZeYKc6yjm-gCEMf62RndS_E1Euj_4
